# Generated by Django 2.0 on 2019-01-25 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0002_auto_20190124_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guardianprofiles',
            old_name='age',
            new_name='occupation',
        ),
        migrations.RemoveField(
            model_name='guardianprofiles',
            name='g_or_t',
        ),
        migrations.RemoveField(
            model_name='guardianprofiles',
            name='image',
        ),
        migrations.RemoveField(
            model_name='guardianprofiles',
            name='name',
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='Guardians_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name="Guardian's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='guardian_contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=14, verbose_name="Guardian's Contact Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='need_tutor_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='nid_No',
            field=models.CharField(default=django.utils.timezone.now, max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='payment',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='s_class',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name="Student's Class"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='school',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='School/College'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='students_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name="Student's Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardianprofiles',
            name='tution_hour',
            field=models.CharField(default=django.utils.timezone.now, max_length=2, verbose_name='Tution hours'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutorprofiles',
            name='phone_number',
            field=models.CharField(max_length=14, verbose_name='Contact Number'),
        ),
    ]
