# Generated by Django 2.0 on 2019-01-25 07:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0003_auto_20190125_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofiles',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
