# Generated by Django 2.0 on 2019-01-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0004_guardianprofiles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorprofiles',
            name='Fathers_Name',
        ),
        migrations.RemoveField(
            model_name='tutorprofiles',
            name='Mothers_Name',
        ),
    ]
