# Generated by Django 2.0 on 2019-01-25 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0005_auto_20190125_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofiles',
            name='address',
            field=models.TextField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
