# Generated by Django 2.0 on 2019-01-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0006_guardianprofiles_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianprofiles',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='tutorprofiles',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1),
        ),
    ]
