# Generated by Django 2.0 on 2019-01-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0007_auto_20190126_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianprofiles',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='tutorprofiles',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
