# Generated by Django 2.0 on 2019-02-12 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0009_auto_20190126_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianprofiles',
            name='week_days',
            field=models.CharField(default=django.utils.timezone.now, max_length=1, verbose_name='How many days in a week?'),
            preserve_default=False,
        ),
    ]
