# Generated by Django 2.0 on 2019-02-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hireapp', '0011_guardianprofiles_number_of_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofiles',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
